---
title: "R Notebook"
output: html_notebook
---


```{r}
install.packages("devtools")
devtools::install_github("naef-lab/dryR")
install.packages('simphony')
install.packages('stringr')

library(tidyverse)
library("dryR")
library(stringr)

```

```{r}
processed_data <- read_csv("Bignon_RNA-seq_processed.csv")
processed_data
```

```{r}

# prepare arguments
countData = simData[["countData"]]
group     = simData[["group"]]
time      = simData[["time"]]

# prefilter
keep <- rowSums(countData) > 0
countData <- countData[keep,]

# run the analysis for count data (e.g. RNA-Seq data)
dryList   = dryseq(countData,group,time)

# explore the results
dryList[["results"]]     # data frame summarizing results
dryList[["parameters"]]  # coefficients: phase, amplitude and mean for each group
dryList[["ncounts"]]     # normalized counts
dryList[["counts"]]      # raw counts
dryList[["cook"]]        # cook's distance for outlier detection
dryList[["BICW_rhythm"]] # BICW for each rhythmic model
dryList[["BICW_mean"]]   # BICW for each mean model

# generate a pdf with a global summary of all models
plot_models_rhythm(dryList, "./")

# plot a feature of interest
dry_plot(dryList, "feature_113")

```

### Generate processed count matrix

```{r}
processed_data
count_data_drylm <- processed_data |>
    column_to_rownames("Gene_ID") |>
    select(-c(Gene_Name, description, Gene_type))

# Check for missing values or empty rows
table(rowSums(count_data_drylm) == 0) 
table(is.na(count_data_drylm))

group_drylm <- as.data.frame(t(count_data_drylm)) |>
    rownames_to_column("Label") |>
    select(Label) |> t()

time_drylm <- str_extract(group_drylm, 'ZT(\\d*)_', group = 1) |> strtoi (base=10)

# test <- 'ZT0_KO3'
group_drylm_new <- str_extract(group_drylm, 'ZT\\d*_(\\D*)', group = 1)
group_drylm_new


```

```{r}

drylm_result = drylm(count_data_drylm,group_drylm_new,time_drylm, period = 24)

# explore the results
drylm_result[["results"]]     # data frame summarizing results
drylm_result[["parameters"]]  # coefficients: phase, amplitude and mean for each group
drylm_result[["ncounts"]]     # normalized counts
drylm_result[["counts"]]      # raw counts (NULL)
drylm_result[["cook"]]        # cook's distance for outlier detection (NULL)
drylm_result[["BICW_rhythm"]] # BICW for each rhythmic model
drylm_result[["BICW_mean"]]   # BICW for each mean model

# generate a pdf with a global summary of all models
plot_models_rhythm(drylm_result, "./")

# plot a feature of interest
dry_plot(drylm_result, "feature_113")



```

This is what the Bignon paper did, they used drylm on logCPM normalised (?) data.

### Generate raw count matrix

```{r}
install.packages("BiocManager")
BiocManager::install("GEOquery")
library(GEOquery)
library(stringr)
library(tidyr)

gse <- getGEO(filename = "~/Circadian-Transcriptomics//Count data/GSE216252_series_matrix.txt.gz", GSEMatrix = TRUE,
    getGPL = FALSE)

meta <- gse[[1]]
gsm <- gse[[2]]
label_df <- as.data.frame(t(rbind(gsm, meta))) |> separate_wider_delim(cols = meta, delim = ", ", names = c("sample", "genotype", "timepoint", "replicate")) |> separate_wider_delim(cols = replicate, delim = " ", names = c("rep", "replicate")) |> separate_wider_delim(cols = genotype, delim = " ", names = c("genotype", "gen"))

label_df <- label_df |>
  mutate(genotype_new = recode(genotype, control = "C", cKO = "KO")) |> 
  mutate(timepoint_new = str_remove(timepoint, "ZT")) |>
  select(gsm, genotype_new, timepoint_new, replicate)


```

```{r}
setwd("~/Circadian-Transcriptomics/Count data/GSE216252_RAW")

file_list <- list.files(".")
count_matrix <- read.delim(file_list[1]) |> select(Gene_ID)

for (file in file_list){
  gsm <- str_extract(file, '([[:alnum:]]*)_\\S*', group = 1)
  count_matrix <- read.delim(file) |> 
      rename_with(~gsm, 2) |> 
    full_join(count_matrix)
}


```

```{r}
summary(count_matrix)
sum(is.na(count_matrix))
count_matrix
```

```{r}
# sort gsm (i.e.) in count_matrix
count_data_dryseq <- count_matrix[1:(nrow(count_matrix)-5),] |> remove_rownames() |>
  column_to_rownames("Gene_ID") 
count_data_dryseq <- count_data_dryseq[,order(colnames(count_data_dryseq))] |> as.matrix()

tail(count_data_dryseq)
  
is.unsorted(label_df$gsm) # check if the metadata is sorted

group_dryseq <- label_df$genotype_new 
time_dryseq <- strtoi(label_df$timepoint_new, base=10)
```


```{r}
# prefilter
keep <- rowSums(count_data_dryseq) > 0
count_data_dryseq <- count_data_dryseq[keep,]
nrow(count_data_dryseq)

dryseq_result = dryseq(count_data_dryseq, group_dryseq, time_dryseq)

# explore the results
dryList[["results"]]     # data frame summarizing results
dryList[["parameters"]]  # coefficients: phase, amplitude and mean for each group
dryList[["ncounts"]]     # normalized counts
dryList[["counts"]]      # raw counts
dryList[["cook"]]        # cook's distance for outlier detection
dryList[["BICW_rhythm"]] # BICW for each rhythmic model
dryList[["BICW_mean"]]   # BICW for each mean model

# generate a pdf with a global summary of all models
plot_models_rhythm(dryList, "./")

# plot a feature of interest
dry_plot(dryList, "feature_113")
```


Bruhhh it seems that the RNA-seq data is too skewed (with a few extremely big values), and it breaks the negative binomial (NB) algorithm in dryseq...


```{r}
as.data.frame(count_data_dryseq[order(rowSums(count_data_dryseq), decreasing=TRUE),])

BiocManager::install("AnnotationHub")
library(AnnotationHub)
library(AnnotationDbi)

ah <- AnnotationHub()

dbResult <- query(ah, c("EnsDb", "Mus musculus", "102"))
dbResult[1]

MouseEnsDb <- ah[[dbResult$ah_id]]
MouseEnsDb
```

- The 
bruhhh okay let's go with drylm first

### Drylm result analysis
```{r}
drylm_result[["parameters"]]
```



test