---
title: "Circadian_pipeline"
output: html_document
date: "2026-01-20"
---

```{r}
library(tidyverse)
library("dryR")
library(stringr)
library(ggplot2)
library(ggpubr)

library(MASS)
library(janitor)
library(naniar)
library(patchwork)
library(scales)
library(cluster)

library(RColorBrewer)
library(ggrepel)
```


```{r}
getwd()
```

```{r}
raw_count <- read_rds("../../data/Bignon_QC_raw_data/salmon.merged.gene_counts.rds")

raw_count <- assays(raw_count)$counts
```

```{r}
Bignon_processed_data <- read_csv("../../data/Bignon_processed_data//Bignon_RNA-seq_processed.csv") |>
  column_to_rownames("Gene_ID") |>
  dplyr::select(-c(Gene_Name, description, Gene_type))
Bignon_processed_data


```


```{r}
# 1. Convert to CPM

# Compute CPM
raw_count_cpm <- as.data.frame(raw_count) |>
  mutate(across(.cols = everything(), .fns = ~ . * 1000000 / sum(.), .names = "{col}"))

# Filter for at least CPM >= 1 in one sample
raw_count_cpm_filtered <- dplyr::filter(raw_count_cpm, apply(raw_count_cpm, 1, max) >= 1)
raw_count_cpm_filtered

Bignon_processed_data_sorted <- Bignon_processed_data[order(rownames(Bignon_processed_data), decreasing=FALSE),]
sum(rownames(raw_count_cpm_filtered) %in% rownames(Bignon_processed_data_sorted))
nrow(raw_count_cpm_filtered)
nrow(Bignon_processed_data_sorted) # Bignon's number of genes detected



```


















